const prompts = [
  "Something I get to do today that I've always wanted to do",
  "A freedom I have that I've always taken for granted",
  "One reason I cherish this time of the year",
  "The best part of today",
  "A quality of one of my closest friends that I absolutely love",
  "What I appreciate most about this moment",
  "A simple pleasure that I'm grateful for",
  "An unexpected kindness I witnessed recently",
  "A recent challenge that has made me stronger",
  "Something beautiful I saw today that made me smile",
  "A lesson I learned this week that I'm thankful for",
  "The sound that brings me peace or joy",
  "A piece of art or music that touched my heart recently",
  "Someone who always makes me laugh and why",
  "A memory that brings me joy whenever I think about it",
  "The most comforting smell I can think of and why it comforts me",
  "An act of kindness I want to do for someone else",
  "A part of my daily routine that I look forward to every day",
  "Something I saw today that was the color of happiness for me",
  "A word that describes my day today and why I chose it",
  "An accomplishment I am proud of and how it has affected my life",
  "A book that changed my perspective on life",
  "A place where I feel completely at peace",
  "An old habit I'm thankful I've left behind",
  "A new skill I've learned this year and how it's been useful",
  "A person who has been a great influence on me",
  "A positive change in my life this year",
  "Something I can do today that I couldn't a year ago",
  "A tradition I love and why it's meaningful to me",
  "A goal I'm working towards and how it will improve my life",
  "A mistake that led to a valuable lesson",
  "A moment this week when I felt truly at peace",
  "A person I'm grateful to have met",
  "A recent realization that has brought me joy",
  "A habit I've developed that has improved my quality of life",
  "The ways in which I've grown over the past year",
  "A kind of weather that uplifts my spirit and why",
  "A family tradition that fills me with happiness",
  "An aspect of my work that I find fulfilling",
  "A talent I have and how I can share it with others",
  "A health milestone I've reached and the journey there",
  "A hobby that brings me joy and how I discovered it",
  "A place in my city that I love visiting",
  "An aspect of my culture that I'm proud of",
  "A comfort food that never fails to make me feel better",
  "The most meaningful compliment I've received",
  "A way in which I've helped someone recently",
  "A piece of advice that has stuck with me",
  "An invention that I'm grateful exists",
  "The most peaceful part of my day",
  "A song that makes me feel happy whenever I hear it",
  "A personal quality I've worked to develop",
  "A positive memory from my childhood",
  "Something in nature that amazes me",
  "A moment when I felt proud of myself",
  "A challenge I've overcome",
  "A small victory I've had recently",
  "Something I'm looking forward to in the future",
  "A way I've made a difference in someone's life",
  "The feeling I get when I help someone",
  "A moment of kindness from a stranger",
  "A positive attribute I've inherited from my family",
  "Something I've done that I never thought I could",
  "A trait I admire in others and strive to cultivate in myself",
  "A moment when I felt connected to the world around me",
  "A time when I laughed so hard, I cried",
  "An experience that has shaped who I am",
  "Something I've created that I'm proud of",
  "A habit that contributes to my well-being",
  "A person who brings out the best in me",
  "A recent experience that made me feel strong",
  "A dream I have for the future",
  "A place where I've made happy memories",
  "A personal tradition that is important to me",
  "A moment in my life when everything felt right",
  "A quality in others that I am grateful for",
  "A change in perspective that has led to growth",
  "A part of my daily life that I once wished for",
  "A positive impact I've made on my community",
]

const getRandomPrompt = () => {
  const randomIndex = Math.floor(Math.random() * prompts.length);
  return prompts[randomIndex];
};

export default getRandomPrompt;